name:
#channels:
#  - bioconda
#  - conda-forge
#dependencies:
#  - r-base
#  - snakemake
#  - samtools
#  - minimap2
#  - bioconductor-rsubread
#  - nanofilt
#  - pandoc

fa_path: /mnt/d/fastq/
srr: SRR2073085