# Paths and directories.
data_path: /media/orfeas/AE9E01139E00D5AD/data/
fa_path: /media/orfeas/AE9E01139E00D5AD/data/fastq/
ref_path: /media/orfeas/AE9E01139E00D5AD/data/ref/
barcode_path: /media/orfeas/AE9E01139E00D5AD/data/barcodes/
log_path: /media/orfeas/AE9E01139E00D5AD/data/log/
adapter_path: /media/orfeas/AE9E01139E00D5AD/data/adapters/

srr: SRR2073085

qual: 0
paired_bool: 0

technology:
  illumina:
    genIndels: 1
    minMapQual: 20
    minBaseQual: 20
  iontorrent:
    genIndels: 0
    minMapQual: 10
    minBaseQual: 10

readlen: 200
minreads: 200